services:
  listings-db:
    image: mysql:8.0.33
    container_name: listings-db
    restart: always
    volumes:
      - listings-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: princess
      MYSQL_DATABASE: listings
    networks:
      - airlock_backend

  listings-service:
    build: .
    ports:
      - "4010:4010"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: princess
      DB_NAME: listings
    networks:
      - airlock_backend

networks:
  airlock_backend:
    driver: bridge

volumes:
  listings-db-data:
