version: '3.9'

services:
  listings-db:
    image: mysql:8.0.33
    container_name: listings-db
    restart: always
    volumes:
      - listings-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: princess
      MYSQL_DATABASE: listings
    networks:
      - backend
      
  accounts-service: 
    build: ./services/accounts
    ports:
      - "4011:4011"
    environment:
      - NODE_ENV=development
    depends_on:
      - accounts-db

  accounts-db:
    image: mongo:latest
    container_name: accounts-db
    restart: always
    volumes:
      - accounts-db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  listings-service:
    build: ./services/listings
    ports:
      - "4010:4010"
    environment:
      NODE_ENV: development
      MYSQL_HOST: listings-db
      MYSQL_PASSWORD: princess
      MYSQL_DB: listings
    depends_on:
      - listings-db
    networks:
      - backend

networks:
  backend:

volumes:
  listings-db-data:
  accounts-db-data:
