federation_version: 2.7.0

supergraph:
  listen: 0.0.0.0:4000

subgraphs:
  users:
    routing_url: http://localhost:4010
  accounts:
    routing_url: http://localhost:4001
  profiles:
    routing_url: http://localhost:4002
  listings:
    routing_url: http://localhost:4003
  bookings:
    routing_url: http://localhost:4004
  carts:
    routing_url: http://localhost:4005
  payments:
    routing_url: http://localhost:4006
  reviews:
    routing_url: http://localhost:4007

plugins:
  - name: apollo
    config:
      key: "service:minshuku-users:EkVfpI-4wFTOV0B4YyGfsQ"
      graph: "flyToWashington-mc4a9o@current"
