headers:
  all:
    request:
      - propagate:
          named: "Authorization"
include_subgraph_errors:
  all: true # Propagate errors from all subgraphs
cors:
  origins:
    - http://localhost:3000 # Allows any locally-running client to run against your Router
    - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
supergraph:
  schema: ./supergraph.graphql
subgraphs:
  users:
    routing_url: http://localhost:4010
  accounts:
    routing_url: http://localhost:4001
  profiles:
    routing_url: http://localhost:4002
  listings:
    routing_url: http://localhost:4003
  bookings:
    routing_url: http://localhost:4004
  carts:
    routing_url: http://localhost:4005
  payments:
    routing_url: http://localhost:4006
  reviews:
    routing_url: http://localhost:4007
 

