headers:
  all:
    request:
      - propagate:
          named: "Authorization"
include_subgraph_errors:
  all: true # Propagate errors from all subgraphs
cors:
  origins:
    - http://localhost:3000 # Allows any locally-running client to run against your Router
    - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
supergraph:
  schema: ./supergraph.graphql
subgraphs:
  users:
    routing_url: http://localhost:4010/graphql
    schema:
      file: ./subgraph-users/schema.graphql
  profiles:
    routing_url: http://localhost:4020/graphql
    schema:
      file: ./subgraph-profiles/schema.graphql    
  accounts:
    routing_url: http://localhost:4030/graphql
    schema:
      file: ./subgraph-accounts/schema.graphql
  listings:
    routing_url: http://localhost:4040/graphql
    schema:
      file: ./subgraph-listings/schema.graphql
  bookings:
    routing_url: http://localhost:4050/graphql
    schema:
      file: ./subgraph-bookings/schema.graphql
  carts:
    routing_url: http://localhost:4060/graphql
    schema:
      file: ./subgraph-carts/schema.graphql
  payments:
    routing_url: http://localhost:4070/graphql
    schema:
      file: ./subgraph-payments/schema.graphql    
  reviews:
    routing_url: http://localhost:4080/graphql
    schema:
      file: ./subgraph-reviews/schema.graphql
 

