supergraph:
  listen: 127.0.0.1:3000

include_subgraph_errors:
  all: true # Propagate errors from all subgraphs

telemetry:
  instrumentation:
    spans:
      mode: spec_compliant

headers:
  all:
    request:
      - propagate:
          named: "Authorization"

cors:
  origins:
    - http://localhost:3000 # Allows any locally-running client to run against your Router
    - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
    - https://your-production-app.com # Add your production app's URL here

# Enable subscriptions
subscription:
  enabled: true
  mode:
    passthrough:
      all:
        path: /ws
