federation_version: =2.7.0
subgraphs:
  users:
    routing_url: http://localhost:4010
    schema:
      file: ./subgraph-users/schema.graphql
  listings:
    routing_url: http://localhost:4040
    schema:
      file: ./subgraph-listings/schema.graphql